title: OmniFYI
description: Tutorials, guides, and ideas
author: Levo

theme: minima
minima:
  skin: auto

show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
default_lang: en
languages: ["en", "hi"]
collections:
  posts_hi:
    output: true
    permalink: /hi/:title/

